spring:
  data:
    mongodb:
      host: tf_mongodb
      port: 27017
      database: customer
      username: tradeflow_admin
      password: tf_strong_password
      authentication-database: admin

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://tf-discovery-server:8761/eureka/
