spring:
  # MongoDB Settings
  data:
    mongodb:
      host: localhost
      port: 50000
      database: customer
      username: tradeflow_admin
      password: tf_strong_password
      authentication-database: admin

  # PostgreSQL settings
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: tradeflow_admin
    password: tf_strong_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8090
